# Generated by Django 5.1.4 on 2024-12-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
