# Generated by Django 5.1.4 on 2024-12-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_likepost_delete_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likepost",
            name="post_id",
            field=models.CharField(max_length=500),
        ),
    ]
